spring:
  application:
    name: retailhub

  # =============================================
  # PostgreSQL 17 Docker (localhost:5434)
  # =============================================
  datasource:
    url: jdbc:postgresql://localhost:5434/retailhub
    username: retailhub
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: retailhub-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0

# =============================================
# JWT
# =============================================
app:
  jwt:
    secret: "CHANGE-ME-IN-PRODUCTION-min-256-bit-secret-key-here-1234567890"
    access-token-expiration: 900       # 15 минут (секунды)
    refresh-token-expiration: 604800   # 7 дней (секунды)

# =============================================
# Swagger UI — http://localhost:8080/swagger-ui.html
# =============================================
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs

server:
  port: 8087
